# Generated by Django 6.0.1 on 2026-01-24 03:47

import swim_backend.images.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('protocol', models.CharField(choices=[('scp', 'SCP'), ('http', 'HTTP'), ('https', 'HTTPS'), ('ftp', 'FTP')], default='scp', max_length=10)),
                ('address', models.CharField(help_text='Hostname or IP (e.g. 10.1.1.5)', max_length=255)),
                ('port', models.IntegerField(default=22)),
                ('base_path', models.CharField(default='/', help_text='Root path for images', max_length=255)),
                ('username', models.CharField(blank=True, max_length=255)),
                ('password', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, help_text='For regional mapping', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255, unique=True)),
                ('version', models.CharField(max_length=50)),
                ('file', models.FileField(upload_to=swim_backend.images.models.image_upload_path)),
                ('size_bytes', models.BigIntegerField(editable=False)),
                ('md5_checksum', models.CharField(blank=True, editable=False, max_length=32, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
