# Generated by Django 6.0.1 on 2026-01-24 04:24

import django.db.models.deletion
import swim_backend.images.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='file_server',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='images.fileserver'),
        ),
        migrations.AddField(
            model_name='image',
            name='is_remote',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='image',
            name='remote_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=swim_backend.images.models.image_upload_path),
        ),
        migrations.AlterField(
            model_name='image',
            name='size_bytes',
            field=models.BigIntegerField(default=0, editable=False),
        ),
    ]
