# Generated by Django 6.0.1 on 2026-01-24 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_image_file_server_image_is_remote_image_remote_path_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileserver',
            name='protocol',
            field=models.CharField(choices=[('scp', 'SCP'), ('sftp', 'SFTP'), ('http', 'HTTP'), ('https', 'HTTPS'), ('ftp', 'FTP')], default='scp', max_length=10),
        ),
    ]
