# Generated by Django 6.0.1 on 2026-01-26 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_alter_fileserver_protocol'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileserver',
            name='is_global_default',
            field=models.BooleanField(default=False, help_text='Fallback server if regional one fails'),
        ),
    ]
