# Generated by Django 6.0.1 on 2026-01-28 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0004_fileserver_is_global_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='filename',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='image',
            name='md5_checksum',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='size_bytes',
            field=models.BigIntegerField(default=0),
        ),
    ]
