# Generated by Django 6.0.1 on 2026-01-24 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicemodel',
            name='golden_image_file',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='devicemodel',
            name='golden_image_version',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
