# Generated by Django 6.0.1 on 2026-01-24 04:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_devicemodel_golden_image_file_and_more'),
        ('images', '0002_image_file_server_image_is_remote_image_remote_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicemodel',
            name='default_file_server',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='images.fileserver'),
        ),
        migrations.AddField(
            model_name='devicemodel',
            name='golden_image_path',
            field=models.CharField(blank=True, help_text='Remote folder path to scan for images', max_length=255, null=True),
        ),
    ]
