# Generated by Django 6.0.1 on 2026-01-24 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_devicemodel_default_file_server_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicemodel',
            name='golden_image_md5',
            field=models.CharField(blank=True, help_text='MD5 Checksum', max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='devicemodel',
            name='golden_image_size',
            field=models.BigIntegerField(blank=True, help_text='Size in bytes', null=True),
        ),
    ]
