# Generated by Django 6.0.1 on 2026-01-26 01:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_devicemodel_golden_image_md5_and_more'),
        ('images', '0004_fileserver_is_global_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='preferred_file_server',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferred_devices', to='images.fileserver'),
        ),
        migrations.AddField(
            model_name='site',
            name='preferred_file_server',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferred_sites', to='images.fileserver'),
        ),
    ]
