# Generated by Django 6.0.1 on 2026-01-26 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0006_region_site_region'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('secret', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='device',
            name='secret',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
