# Generated by Django 6.0.1 on 2026-01-28 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0007_globalcredential_device_secret_alter_device_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='boot_method',
            field=models.CharField(blank=True, help_text='System image file path or boot method', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='reachability',
            field=models.CharField(choices=[('Reachable', 'Reachable'), ('Unreachable', 'Unreachable'), ('Unknown', 'Unknown')], default='Unknown', max_length=20),
        ),
    ]
