# Generated by Django 6.0.1 on 2026-01-28 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0008_device_boot_method_alter_device_reachability'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='mac_address',
            field=models.CharField(blank=True, help_text='Device MAC Address', max_length=100, null=True),
        ),
    ]
