# Generated by Django 6.0.1 on 2026-01-28 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0009_device_mac_address'),
        ('images', '0004_fileserver_is_global_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicemodel',
            name='default_image',
            field=models.ForeignKey(blank=True, help_text='The Golden Image', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_models', to='images.image'),
        ),
        migrations.AddField(
            model_name='devicemodel',
            name='supported_images',
            field=models.ManyToManyField(blank=True, help_text='List of allowed images', related_name='supported_models', to='images.image'),
        ),
    ]
