# Generated by Django 6.0.1 on 2026-01-28 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0010_devicemodel_default_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={'permissions': [('can_sync_device', 'Can sync device inventory'), ('can_upgrade_device', 'Can upgrade device firmware'), ('can_check_readiness', 'Can check device readiness')]},
        ),
    ]
