# Generated by Django 6.0.1 on 2026-01-28 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0011_add_custom_permissions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={'ordering': ['hostname'], 'permissions': [('can_sync_device', 'Can sync device inventory'), ('can_upgrade_device', 'Can upgrade device firmware'), ('can_check_readiness', 'Can check device readiness')]},
        ),
    ]
