# Generated by Django 6.0.1 on 2026-01-29 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0012_alter_device_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={'ordering': ['hostname'], 'permissions': [('sync_device_inventory', 'Can sync device inventory'), ('upgrade_device_firmware', 'Can upgrade device firmware'), ('check_device_readiness', 'Can check device readiness')]},
        ),
    ]
