# Generated by Django 6.0.1 on 2026-01-24 03:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
        ('images', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidationCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('check_type', models.CharField(choices=[('pre', 'Pre-Check'), ('post', 'Post-Check'), ('both', 'Both')], default='both', max_length=10)),
                ('category', models.CharField(choices=[('script', 'Custom Script'), ('genie', 'Genie Feature')], default='script', max_length=20)),
                ('command', models.CharField(help_text='Python path or Genie feature name', max_length=255)),
                ('is_default', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('scheduled', 'Scheduled'), ('distributing', 'Distributing'), ('distributed', 'Distributed'), ('activating', 'Activating'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('distribution_time', models.DateTimeField(blank=True, null=True)),
                ('activation_time', models.DateTimeField(blank=True, null=True)),
                ('activate_after_distribute', models.BooleanField(default=True)),
                ('cleanup_flash', models.BooleanField(default=False)),
                ('steps', models.JSONField(blank=True, default=list)),
                ('log', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='devices.device')),
                ('file_server', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='images.fileserver')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='images.image')),
                ('selected_checks', models.ManyToManyField(blank=True, to='core.validationcheck')),
            ],
        ),
        migrations.CreateModel(
            name='CheckRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('output', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_runs', to='devices.device')),
                ('validation_check', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.validationcheck')),
            ],
        ),
        migrations.CreateModel(
            name='GoldenImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=50)),
                ('site', models.CharField(default='Global', max_length=100)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='images.image')),
            ],
            options={
                'unique_together': {('platform', 'site')},
            },
        ),
    ]
