# Generated by Django 6.0.1 on 2026-01-25 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_job_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='task_name',
            field=models.CharField(default='Upgrade-Task', max_length=100),
        ),
    ]
