# Generated by Django 6.0.1 on 2026-01-25 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_job_task_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='batch_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='execution_mode',
            field=models.CharField(choices=[('parallel', 'Parallel'), ('sequential', 'Sequential')], default='parallel', max_length=20),
        ),
    ]
