# Generated by Django 6.0.1 on 2026-01-25 04:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_job_batch_id_job_execution_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkrun',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='check_runs', to='core.job'),
        ),
    ]
