# Generated by Django 6.0.1 on 2026-01-26 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_workflow_job_workflow_workflowstep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowstep',
            name='step_type',
            field=models.CharField(choices=[('readiness', 'Readiness Check'), ('distribution', 'Software Distribution'), ('precheck', 'Pre-Checks'), ('activation', 'Activation'), ('postcheck', 'Post-Checks'), ('wait', 'Wait Step'), ('ping', 'Reachability Check'), ('custom', 'Custom Action')], max_length=50),
        ),
    ]
