# Generated by Django 6.0.1 on 2026-01-28 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_workflowstep_step_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validationcheck',
            name='category',
            field=models.CharField(choices=[('script', 'Custom Script'), ('genie', 'Genie Feature'), ('command', 'Custom Command')], default='script', max_length=20),
        ),
    ]
