# Generated by Django 6.0.1 on 2026-01-28 16:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0008_alter_validationcheck_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionBundle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('enabled', models.BooleanField(default=True)),
                ('can_view', models.BooleanField(default=False)),
                ('can_add', models.BooleanField(default=False)),
                ('can_change', models.BooleanField(default=False)),
                ('can_delete', models.BooleanField(default=False)),
                ('additional_actions', models.TextField(blank=True, help_text="Comma-separated list of custom actions like 'sync', 'upgrade', 'export'", null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, related_name='permission_bundles', to='auth.group')),
                ('object_types', models.ManyToManyField(blank=True, help_text='Models this permission applies to', related_name='permission_bundles', to='contenttypes.contenttype')),
                ('users', models.ManyToManyField(blank=True, related_name='permission_bundles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Permission Bundle',
                'verbose_name_plural': 'Permission Bundles',
                'ordering': ['name'],
            },
        ),
    ]
