# Generated by Django 6.0.1 on 2026-01-28 17:23

import django.db.models.deletion
import swim_backend.core.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_add_permission_bundles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='APIToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default=swim_backend.core.models.APIToken.generate_token, max_length=100, unique=True)),
                ('write_enabled', models.BooleanField(default=True, help_text='Permit create/update/delete operations using this key')),
                ('expires', models.DateTimeField(blank=True, help_text='Token expiration date/time (optional)', null=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('allowed_ips', models.TextField(blank=True, help_text='Allowed IPv4/IPv6 networks (comma-separated)')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'API Token',
                'verbose_name_plural': 'API Tokens',
                'ordering': ['-created'],
            },
        ),
    ]
