# Generated by Django 6.0.1 on 2026-01-29 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_add_activity_logs'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardProxy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Dashboard',
                'verbose_name_plural': 'Dashboard',
                'permissions': [('view_dashboard', 'Can view dashboard')],
                'managed': False,
                'default_permissions': (),
            },
        ),
    ]
