# Generated by Django 6.0.1 on 2026-01-29 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_dashboardproxy'),
    ]

    operations = [        migrations.CreateModel(
            name='DashboardProxy',
            fields=[
            ],
            options={
                'managed': False,
                'default_permissions': (),
                'permissions': [('view_dashboard', 'Can view dashboard')],
                'verbose_name': 'Dashboard',
                'verbose_name_plural': 'Dashboard',
            },
        ),    ]
