# Generated by Django 6.0.1 on 2026-01-30 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_add_dashboard_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='task_name',
            field=models.CharField(default='Distribution-Task', max_length=100),
        ),
    ]
