# Generated by Django 6.0.1 on 2026-01-30 11:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_job_task_name'),
        ('devices', '0013_alter_device_options'),
        ('images', '0005_remove_filename_unique'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ZTPWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('device_family_filter', models.CharField(blank=True, help_text='Filter by device family (Switch, Router, etc.)', max_length=50)),
                ('platform_filter', models.CharField(blank=True, help_text='Filter by platform (iosxe, nxos, etc.)', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('discovering', 'Discovering Devices'), ('provisioning', 'Provisioning'), ('upgrading', 'Upgrading'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('total_devices', models.IntegerField(default=0)),
                ('completed_devices', models.IntegerField(default=0)),
                ('failed_devices', models.IntegerField(default=0)),
                ('auto_execute', models.BooleanField(default=False, help_text='Automatically start provisioning when devices are discovered')),
                ('schedule_time', models.DateTimeField(blank=True, help_text='Schedule execution for specific time', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('devices_discovered', models.ManyToManyField(blank=True, related_name='ztp_workflows', to='devices.device')),
                ('model_filter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='devices.devicemodel')),
                ('target_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='images.image')),
                ('target_site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='devices.site')),
                ('workflow', models.ForeignKey(blank=True, help_text='Upgrade workflow to use', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.workflow')),
            ],
            options={
                'verbose_name': 'ZTP Workflow',
                'verbose_name_plural': 'ZTP Workflows',
                'ordering': ['-created_at'],
            },
        ),
    ]
