# Generated by Django 6.0.1 on 2026-01-30 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_ztpworkflow'),
        ('devices', '0013_alter_device_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ztpworkflow',
            name='auto_execute',
        ),
        migrations.RemoveField(
            model_name='ztpworkflow',
            name='devices_discovered',
        ),
        migrations.RemoveField(
            model_name='ztpworkflow',
            name='schedule_time',
        ),
        migrations.RemoveField(
            model_name='ztpworkflow',
            name='target_image',
        ),
        migrations.AddField(
            model_name='ztpworkflow',
            name='devices_provisioned',
            field=models.ManyToManyField(blank=True, related_name='ztp_workflows', to='devices.device'),
        ),
        migrations.AddField(
            model_name='ztpworkflow',
            name='skipped_devices',
            field=models.IntegerField(default=0, help_text='Devices skipped (already compliant or no golden image)'),
        ),
        migrations.AddField(
            model_name='ztpworkflow',
            name='webhook_token',
            field=models.CharField(blank=True, help_text='Secret token for webhook authentication', max_length=100),
        ),
        migrations.AlterField(
            model_name='ztpworkflow',
            name='device_family_filter',
            field=models.CharField(blank=True, help_text='Filter by device family (optional)', max_length=50),
        ),
        migrations.AlterField(
            model_name='ztpworkflow',
            name='model_filter',
            field=models.ForeignKey(blank=True, help_text='Filter by model (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='devices.devicemodel'),
        ),
        migrations.AlterField(
            model_name='ztpworkflow',
            name='platform_filter',
            field=models.CharField(blank=True, help_text='Filter by platform (optional)', max_length=50),
        ),
        migrations.AlterField(
            model_name='ztpworkflow',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('archived', 'Archived')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='ztpworkflow',
            name='target_site',
            field=models.ForeignKey(blank=True, help_text='Restrict to specific site (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='devices.site'),
        ),
        migrations.AlterField(
            model_name='ztpworkflow',
            name='total_devices',
            field=models.IntegerField(default=0, help_text='Total devices processed'),
        ),
        migrations.AlterField(
            model_name='ztpworkflow',
            name='workflow',
            field=models.ForeignKey(blank=True, help_text='Upgrade workflow to use for auto-provisioning', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.workflow'),
        ),
    ]
