# Generated by Django 6.0.1 on 2026-01-30 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_ztpworkflow_auto_execute_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ztpworkflow',
            name='postcheck_validations',
            field=models.ManyToManyField(blank=True, help_text='Post-checks to run after provisioning', limit_choices_to={'check_type__in': ['post', 'both']}, related_name='ztp_postchecks', to='core.validationcheck'),
        ),
        migrations.AddField(
            model_name='ztpworkflow',
            name='precheck_validations',
            field=models.ManyToManyField(blank=True, help_text='Pre-checks to run before provisioning', limit_choices_to={'check_type__in': ['pre', 'both']}, related_name='ztp_prechecks', to='core.validationcheck'),
        ),
    ]
