# Generated by Django 6.0.2 on 2026-02-16 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_ztpworkflow_postcheck_validations_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ztpworkflow',
            options={'ordering': ['-created_at'], 'permissions': [('can_view_ztp', 'Can view ZTP workflows'), ('can_manage_ztp', 'Can create/edit ZTP workflows'), ('can_execute_ztp', 'Can execute ZTP provisioning'), ('can_delete_ztp', 'Can delete ZTP workflows')], 'verbose_name': 'ZTP Workflow', 'verbose_name_plural': 'ZTP Workflows'},
        ),
    ]
