# Generated by Django 6.0.1 on 2026-02-16 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_ztpworkflow_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='remarks',
            field=models.TextField(blank=True, help_text='RFC number or comments', null=True),
        ),
    ]
